### ISSUE TITLE
Can't use $default in other parts of build_config

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1075]
Source: https://github.com/dart-lang/build/issues/1073#issuecomment-369627741

That might be WAI, but we should fail nicer then.

```
[INFO] Entrypoint: Generating build script completed, took 267ms
NoSuchMethodError: The getter 'target' was called on null.
Receiver: null
Tried calling: target
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      createBuildActions.<anonymous closure> (package:build_runner/src/package_graph/apply_builders.dart:114:22)
#2      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:44:24)
#3      stronglyConnectedComponents (package:graphs/src/strongly_connected_components.dart:66:55)
#4      createBuildActions (package:build_runner/src/package_graph/apply_builders.dart:112:16)
<asynchronous suspension>
#5      build (package:build_runner/src/generate/build_impl.dart:93:13)
```

**Comment by matanlurey** [comment]
If this is a legit use-case I'd love to help.

**Comment by natebosch** [comment]
yeah I think this is worth supporting.

Fixing this will involve something like updating [`normalizeTargetUsage`](https://github.com/dart-lang/build/blob/91d76a5e7e6b280827b5f4165d2932cf5619f5a3/build_config/lib/src/key_normalization.dart#L47) to understand `_defaultTargetNamePlaceholder`

**Comment by matanlurey** [comment]
Ack! Unless you need it on a schedule I can take this one.

**Comment by matanlurey** [comment]
As-per @natebosch on latest (closed PR #1113) we just need to release build_config.
