### ISSUE TITLE
The getter 'offset' was called on null.

### ISSUE THREAD

**Issue by Meai** [dart-lang/build#1092]
No idea why I'm getting this one now, in the stacktrace it indicates on some missing imports but I'm not getting the error message because it errors out first, I think:

```
pc@linux-j75p:~/projects/css-grid> pub run build_runner watch --output build
[INFO] Entrypoint: Generating build script completed, took 192ms
[INFO] Watch: Setting up file watchers completed, took 39ms
[INFO] Watch: Waiting for all file watchers to be ready completed, took 107ms
[INFO] BuildDefinition: Building new asset graph completed, took 402ms
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] Instance of 'WebEntrypointBuilder' on apgui|web/main.dart: 
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
[SEVERE] Build: Failed after 3.5s
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _missingImportMessage (package:build_modules/src/errors.dart:99:53)
<asynchronous suspension>
#2      MissingModulesException.create (package:build_modules/src/errors.dart:76:21)
<asynchronous suspension>
#3      Module.computeTransitiveDependencies (package:build_modules/src/modules.dart:141:43)
<asynchronous suspension>
#4      _ensureTransitiveModules (package:build_web_compilers/src/dev_compiler_bootstrap.dart:92:37)
<asynchronous suspension>
#5      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:31:30)
<asynchronous suspension>
#6      WebEntrypointBuilder.build (package:build_web_compilers/src/web_entrypoint_builder.dart:104:15)
<asynchronous suspension>
#7      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:43:21)
<asynchronous suspension>
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:343)
#10     Future.wait (dart:async/future.dart:385)
#11     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:49:36)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     runZoned (dart:async/zone.dart:1490)
#15     scopeLogAsync (package:build/src/builder/logging.dart:20:3)
#16     runBuilder (package:build/src/generate/run_builder.dart:49:9)
<asynchronous suspension>
#17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:428:15)
#18     _NoOpBuilderActionTracker.track (package:build_runner/src/generate/performance_tracker.dart:246:73)
#19     _SingleBuild._runForInput (package:build_runner/src/generate/build_impl.dart:427:19)
<asynchronous suspension>
#20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:356:9)
#21     MappedIterator.moveNext (dart:_internal/iterable.dart:392)
#22     Future.wait (dart:async/future.dart:385)
#23     _SingleBuild._runBuilder (package:build_runner/src/generate/build_impl.dart:355:36)
<asynchronous suspension>
#24     _SingleBuild._runPhases.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:301:30)
<asynchronous suspension>
#25     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner/src/generate/performance_tracker.dart:140:15)
#26     _SingleBuild._runPhases (package:build_runner/src/generate/build_impl.dart:298:33)
<asynchronous suspension>
#27     _SingleBuild._safeBuild.<anonymous closure>.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:266:43)
#28     logTimedAsync (package:build_runner/src/logging/logging.dart:26:30)
<asynchronous suspension>
#29     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:265:26)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1490)
#33     _SingleBuild._safeBuild (package:build_runner/src/generate/build_impl.dart:263:5)
#34     _SingleBuild.run (package:build_runner/src/generate/build_impl.dart:200:24)
<asynchronous suspension>
#35     BuildImpl.run (package:build_runner/src/generate/build_impl.dart:145:30)
#36     BuildImpl.create (package:build_runner/src/generate/build_impl.dart:152:37)
<asynchronous suspension>
#37     WatchImpl._run.<anonymous closure> (package:build_runner/src/generate/watch_impl.dart:275:31)
<asynchronous suspension>
#38     WatchImpl._run (package:build_runner/src/generate/watch_impl.dart:283:6)
#39     new WatchImpl (package:build_runner/src/generate/watch_impl.dart:160:9)
#40     runWatch (package:build_runner/src/generate/watch_impl.dart:115:9)
#41     watch (package:build_runner/src/generate/watch_impl.dart:94:7)
<asynchronous suspension>
#42     watch (package:build_runner/src/generate/build.dart:124:5)
#43     _WatchCommand.run (package:build_runner/src/entrypoint/options.dart:297:25)
<asynchronous suspension>
#44     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#45     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#46     new Future.sync (dart:async/future.dart:222)
#47     CommandRunner.run (package:args/command_runner.dart:109:11)
#48     run (package:build_runner/src/entrypoint/run.dart:15:24)
<asynchronous suspension>
#49     main (file:///home/pc/.local/share/Trash/files/css-grid/.dart_tool/build/entrypoint/build.dart:35:22)
<asynchronous suspension>
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

**Comment by jakemac53** [comment]
Ya so if we find an error that looks like it was caused by a bad import we try and find that import and then print out the actual input statement and location in the file. It looks like for whatever reason in this case the ast node for the import is missing the location information.

**Comment by Meai** [comment]
this is some kind of caching problem, I deleted all my dart files in the project and run the build command again and the error still shows

**Comment by Meai** [comment]
ok I dont know what this was initially but the terminal that was open somehow pointed to an old deleted folder inode I guess, so I was never running build with any modified files. Thanks Linux...really

**Comment by jakemac53** [comment]
There is a legit bug here still, have a pr out to fix now though
