### ISSUE TITLE
Misleading error message when import is missing and part directive is used

### ISSUE THREAD

**Issue by AlexanderJohr** [dart-lang/build#1123]
Dart SDK Version [ 2.0.0-dev.32.0 ]
Package [ build_modules 0.2.0+1 ]
System [ windows_x64 ]

I use json_serializable to generate a part file with toJson and fromJson methods. To reproduce the error I inserted one missing import:

```dart
library project.serializables.site_page;

import 'package:project/src/serializables/has_parent_page.dart'; // missing
import 'package:json_annotation/json_annotation.dart';

part 'site_page.g.dart';

@JsonSerializable(includeIfNull: false, nullable: false)
class SitePage extends NavigationEntity with _$SitePageSerializerMixin {
```
When running pub run build_runner (serve | build) I got an error, but not which import is wrong. Instead:

```
[SEVERE] Build: Failed after 1m 50s
NoSuchMethodError: The getter 'stringValue' was called on null.
Receiver: null
Tried calling: stringValue
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _missingImportMessage.<anonymous closure> (package:build_modules/src/errors.dart:94:35)
#2      Iterable.firstWhere (dart:core/iterable.dart:584)
#3      _missingImportMessage (package:build_modules/src/errors.dart:93:56)
<asynchronous suspension>
#4      MissingModulesException.create (package:build_modules/src/errors.dart:76:21)
<asynchronous suspension>
#5      Module.computeTransitiveDependencies (package:build_modules/src/modules.dart:141:43)
```

I debugged to the line package:build_modules/src/errors.dart:94 and found out the creation of the correct Exception was interrupted. uri of PartOfDirectiveImpl is null and stringValue can't be invoked.

```dart
Future<String> _missingImportMessage(
    AssetId sourceId, AssetId missingId, AssetReader reader) async {
  var contents = await reader.readAsString(sourceId);
  var parsed = parseDirectives(contents, suppressErrors: true);
  var import =
      parsed.directives.whereType<UriBasedDirective>().firstWhere((directive) {
                    // directive = PartOfDirectiveImpl "part of project.serializables.site_page;"
                             // uri = null
    var uriString = directive.uri.stringValue; 
    if (uriString.startsWith('dart:')) return false;
    var id = new AssetId.resolve(uriString, from: sourceId);
    return id == missingId;
  }, orElse: () => null);
  var lineInfo = parsed.lineInfo.getLocation(import.offset);
  return '`$import` from $sourceId at $lineInfo';
}
```dart

**Comment by jakemac53** [comment]
Thanks for the detailed bug report! Will work on fixing this asap.

**Comment by jakemac53** [comment]
Ugh, this is caused by https://github.com/dart-lang/sdk/issues/32423. Tldr; don't use `whereType` yet!
