### ISSUE TITLE
ConcurrentModificationError using findAssets()

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1128]
I'm writing an aggregate builder, and ran into this error:

```
Build failed!
Error:

Concurrent modification during iteration: _LinkedHashMap len:574.

Stack Trace:

#0      _CompactIterator.moveNext (dart:collection-patch/dart:collection/compact_hash.dart:438)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:438)
#2      SingleStepReader.findAssets (package:build_runner/src/asset/reader.dart:142:22)
#3      BuildStepImpl.findAssets (package:build/src/builder/build_step_impl.dart:91:22)
#4      DebugIndexBuilder.build (package:build_test/src/debug_test_builder.dart:131:41)
#5      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:43:21)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:343)
#8      Future.wait (dart:async/future.dart:385)
#9      runBuilder. (package:build/src/generate/run_builder.dart:49:36)
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1490)
#13     scopeLogAsync (package:build/src/builder/logging.dart:20:3)
#14     runBuilder (package:build/src/generate/run_builder.dart:49:9)
#15     _SingleBuild._runForInput. (package:build_runner/src/generate/build_impl.dart:416:15)
#16     _NoOpBuilderActionTracker.track (package:build_runner/src/generate/performance_tracker.dart:246:73)
#17     _SingleBuild._runForInput (package:build_runner/src/generate/build_impl.dart:415:19)
#18     _SingleBuild._runBuilder. (package:build_runner/src/generate/build_impl.dart:344:20)
#19     MappedIterator.moveNext (dart:_internal/iterable.dart:392)
#20     Future.wait (dart:async/future.dart:385)
#21     _SingleBuild._runBuilder (package:build_runner/src/generate/build_impl.dart:343:36)
#22     _SingleBuild._runPhases. (package:build_runner/src/generate/build_impl.dart:302:19)
#23     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner/src/generate/performance_tracker.dart:140:15)
#24     _SingleBuild._runPhases (package:build_runner/src/generate/build_impl.dart:298:33)
#25     _SingleBuild._safeBuild.. (package:build_runner/src/generate/build_impl.dart:266:43)
#26     logTimedAsync (package:build_runner/src/logging/logging.dart:26:30)
#27     _SingleBuild._safeBuild. (package:build_runner/src/generate/build_impl.dart:265:26)
#28     _rootRun (dart:async/zone.dart:1126)
#29     _CustomZone.run (dart:async/zone.dart:1023)
#30     runZoned (dart:async/zone.dart:1490)
#31     _SingleBuild._safeBuild (package:build_runner/src/generate/build_impl.dart:263:5)
#32     _SingleBuild.run (package:build_runner/src/generate/build_impl.dart:200:24)
#33     BuildImpl.run (package:build_runner/src/generate/build_impl.dart:145:30)
#34     BuildImpl.create (package:build_runner/src/generate/build_impl.dart:152:37)
#35     WatchImpl._run. (package:build_runner/src/generate/watch_impl.dart:275:31)
#36     WatchImpl._run (package:build_runner/src/generate/watch_impl.dart:283:6)
#37     new WatchImpl (package:build_runner/src/generate/watch_impl.dart:160:9)
#38     runWatch (package:build_runner/src/generate/watch_impl.dart:115:9)
#39     watch (package:build_runner/src/generate/watch_impl.dart:94:7)
#40     watch (package:build_runner/src/generate/build.dart:124:5)
#41     _ServeCommand.run (package:build_runner/src/entrypoint/options.dart:345:25)
#42     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
#43     CommandRunner.run. (package:args/command_runner.dart:109:29)
#44     new Future.sync (dart:async/future.dart:222)
#45     CommandRunner.run (package:args/command_runner.dart:109:11)
#46     run (package:build_runner/src/entrypoint/run.dart:15:24)
#47     main (file:///Users/matanl/git/build/e2e_example/.dart_tool/build/entrypoint/build.dart:45:22)
#48     _startIsolate. (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by natebosch** [comment]
yikes. We probably need to make a copy to iterate over.
