### ISSUE TITLE
Watcher crashed for emacs temp file

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/build#1134]
Edited a file in emacs, which created a temporary file, while running `build_runner serve`, and got the crash listed below:
```
FormatException: Invalid character (at character 37)
examples.registration_form/address/.#address_component.html
                                    ^

#0      _Uri._fail (dart:core/uri.dart:1597)
#1      _Uri._normalize (dart:core/uri.dart:2292)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2248)
#3      _Uri._makePath (dart:core/uri.dart:2096)
#4      new _Uri (dart:core/uri.dart:1497)
#5      AssetId.uri (package:build/src/asset/id.dart:102:13)
#6      PackageGraphWatcher._watch.<anonymous closure>.<anonymous closure> (package:build_runner/src/watcher/graph_watcher.dart:84:54)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#11     _MapStream._handleData (dart:async/stream_pipe.dart:232)
#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#16     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379)
#17     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#20     _DelayedData.perform (dart:async/stream_impl.dart:578)
#21     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#25     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#26     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by jakemac53** [comment]
Geeze, we should possibly just catch any uri.parse error and assume its a garbage file?

**Comment by natebosch** [comment]
The stack trace here is in the watcher, we only turn it into a URI for a `log.finest` (which we ignore anyway) - that one would be easy to fix.

We also have a problem if the file is used in a build. If I create a file named `lib/#something.dart` then even a `build` command fails.
