### ISSUE TITLE
e2e_example/tool/build_kernel.dart not working on Win machines

### ISSUE THREAD

**Issue by yury-yufimov** [dart-lang/build#1196]
It seems that DDC with Kernel mode is broken for windows machines.
I try run "dart tool\build_kernel.dart build" and get following error:

```
[WARNING] build_modules|modules on package:path/src/characters.module:
Error creating path|lib/src/characters.unlinked.sum:
Error creating kernel summary for module:path|lib/src/characters.dill

c:: Error: Unable to read '.packages' file:
  FileSystemException(uri=c:; message=StandardFileSystem only supports file:* and data:* URIs).
Crash when compiling null,
at character offset null:
FileSystemException(uri=file:///; message=The system cannot find the path specified.
)
#0      _IoFileSystemEntity.readAsBytes (package:front_end/src/api_prototype/standard_file_system.dart:65)
<asynchronous suspension>
#1      MultiRootFileSystemEntity.readAsBytes (package:front_end/src/multi_root_file_system.dart:76)
<asynchronous suspension>
#2      ProcessedOptions.loadSdkSummaryBytes (package:front_end/src/base/processed_options.dart:140)
<asynchronous suspension>
#3      ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:314)
<asynchronous suspension>
#4      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:60)
<asynchronous suspension>
#5      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:31)
<asynchronous suspension>
#6      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1501)
#10     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#11     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:116)
#12     generateKernel (package:front_end/src/kernel_generator_impl.dart:30)
<asynchronous suspension>
#13     compile (package:front_end/src/api_unstable/summary_worker.dart:58)
<asynchronous suspension>
#14     computeSummary (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/utils/bazel/kernel_summary_worker.dart:145)
<asynchronous suspension>
...
```
I have Windows 10 machine and
> Dart VM version: 2.0.0-dev.39.0 (Fri Mar 16 00:17:07 2018 +0100) on "windows_x64"

installed. 
Error is not reproduced on Linux machine

**Comment by matanlurey** [comment]
Building based on kernel is currently not supported.

**Comment by natebosch** [comment]
This file exists as a development tool to see the impact of future changes in the SDK. Once this becomes a supported build path we'll be sure to get everything working on Windows.
