### ISSUE TITLE
pub run build_runner serve crash

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/build#1628]
When I execute `pub run build_runner serve` on dart SDK: 2.0.0-dev.66.0 (Linux 64 bit)
and with no custom build options, it crashes with the following error:
```
[INFO] Generating build script...Unhandled exception:
type '_CompactLinkedHashSet<dynamic>' is not a subtype of type 'Set<NestingLevel>' of 'usedNesting'
#0      SolveState._calculateSplits (package:dart_style/src/line_splitting/solve_state.dart:293:15)
#1      new SolveState (package:dart_style/src/line_splitting/solve_state.dart:110:5)
#2      LineSplitter.apply (package:dart_style/src/line_splitting/line_splitter.dart:166:20)
#3      LineWriter._completeLine (package:dart_style/src/line_writer.dart:154:27)
#4      LineWriter.writeLines (package:dart_style/src/line_writer.dart:113:11)
#5      ChunkBuilder.end (package:dart_style/src/chunk_builder.dart:564:25)
#6      SourceVisitor.run (package:dart_style/src/source_visitor.dart:105:20)
#7      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:132:26)
#8      DartFormatter.format (package:dart_style/src/dart_formatter.dart:65:12)
#9      _generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:38:30)
<asynchronous suspension>
#10     generateBuildScript.<anonymous closure> (package:build_runner/src/build_script_generate/build_script_generate.dart:24:11)
#11     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
<asynchronous suspension>
#12     generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:21:59)
#13     main (file:///home/patrick/.pub-cache/hosted/pub.dartlang.org/build_runner-0.9.1/bin/build_runner.dart:59:27)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

pubspec.yaml
```
dependencies:
  ...
  sass_builder: ^2.0.3

dev_dependencies:
  build_runner: ^0.9.1
  build_web_compilers: ^0.4.0+4

dependency_overrides:
  analyzer: 0.32.2
```

edit: It works on 2.0.0-dev.65

**Comment by MikeMitterer** [comment]
The same here on my Mac...

**Comment by jakemac53** [comment]
It sounds like you need to update your dependencies to the latest
