### ISSUE TITLE
Print a more helpful error when build.yaml parsing fails

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#2143]
Had a `build.yaml` with invalid content.

We should catch this case and print out something more helpful, referencing the `build.yaml` file by path, etc.

Output:

```
[INFO] Builds finished. Safe to exit
[INFO] Generating build script...Unhandled exception:
Error on line 9, column 5: Could not find expected ':' for simple key.
  ╷
9 │     required_inputs
  │     ^
  ╵
#0      Scanner._removeSimpleKey (package:yaml/src/scanner.dart:526:7)
#1      Scanner._fetchStreamEnd (package:yaml/src/scanner.dart:598:5)
#2      Scanner._fetchNextToken (package:yaml/src/scanner.dart:356:7)
#3      Scanner._fetchMoreTokens (package:yaml/src/scanner.dart:339:7)
#4      Scanner.peek (package:yaml/src/scanner.dart:317:27)
...
```

**Comment by jakemac53** [comment]
We do this now
