### ISSUE TITLE
Missing modules exception doesn't list which modules are missing

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/build#2425]
This happens in https://github.com/flutter/flutter/pull/38773 for `flutter test --platform=chrome`. I think the issue is that there is still a dart:io import somewhere, which is causing a module to get skipped.

Example stack:
```
["flutter_tools:test_entrypoint on test/hello_test.dart.browser_test.dart",["","Unable to find modules for some sources, this is usually the result of either a\nbad import, a missing dependency in a package (or possibly a dev_dependency\nneeds to move to a real dependency), or a build failure (if importing a\ngenerated file).\n\nPlease check the following imports:\n\n","#0      Module.computeTransitiveDependencies (package:build_modules/src/modules.dart:168:7)\n<asynchronous suspension>\n#1      _ensureTransitiveJsModules (package:build_web_compilers/src/dev_compiler_bootstrap.dart:139:37)\n<asynchronous suspension>\n#2      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:34:33)\n<asynchronous suspension>\n#3      FlutterWebTestEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:199:11)\n<asynchronous suspension>\n#4      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:45:21)\n<asynchronous suspension>\n#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)\n#6      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)\n#7      Future.wait (dart:async/future.dart:393:26)\n#8      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:51:36)\n#9      _rootRun (dart:async/zone.dart:1124:13)\n#10     _CustomZone.run (dart:async/zone.dart:1021:19)\n#11     _runZoned (dart:async/zone.dart:1516:10)\n#12     runZoned (dart:async/zone.dart:1500:12)\n#13     scopeLogAsync (package:build/src/builder/logging.dart:22:3)\n#14     runBuilder (package:build/src/generate/run_builder.dart:51:9)\n<asynchronous suspension>\n#15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:471:19)\n#16     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)\n#17     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:469:23)\n<asynchronous suspension>\n#18     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)\n#19     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:428:22)\n#20     Pool.withResource (package:pool/pool.dart:127:28)\n<asynchronous suspension>\n#21     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:424:17)\n#22     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)\n#23     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)\n#24     Future.wait (dart:async/future.dart:393:26)\n#25     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)\n<asynchronous suspension>\n#26     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:320:20)\n<asynchronous suspension>\n#27     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)\n#28     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:316:47)\n<asynchronous suspension>\n#29     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)\n#30     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:310:32)\n#31     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)\n<asynchronous suspension>\n#32     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:267:26)\n<asynchronous suspension>\n#33     _rootRun (dart:async/zone.dart:1124:13)\n#34     _CustomZone.run (dart:async/zone.dart:1021:19)\n#35     _runZoned (dart:async/zone.dart:1516:10)\n#36     runZoned (dart:async/zone.dart:1500:12)\n#37     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:262:5)\n#38     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:209:24)\n<asynchronous suspension>\n#39     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:97:42)\n#40     BuildRunnerWebCompilationProxy._runBuilder (package:flutter_tools/src/build_runner/web_compilation_delegate.dart:157:21)\n<asynchronous suspension>\n#41     BuildRunnerWebCompilationProxy.initialize (package:flutter_tools/src/build_runner/web_compilation_delegate.dart:92:22)\n<asynchronous suspension>\n#42     runTests (package:flutter_tools/src/test/runner.dart:69:51)\n<asynchronous suspension>\n#43     TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:225:30)\n<asynchronous suspension>\n#44     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)\n<asynchronous suspension>\n#45     _rootRun (dart:async/zone.dart:1124:13)\n#46     _CustomZone.run (dart:async/zone.dart:1021:19)\n#47     _runZoned (dart:async/zone.dart:1516:10)\n#48     runZoned (dart:async/zone.dart:1463:12)\n#49     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)\n<asynchronous suspension>\n#50     FastFlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:679:20)\n#51     CommandRunner.runCommand (package:args/command_runner.dart:197:27)\n<asynchronous suspension>\n#52     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)\n<asynchronous suspension>\n#53     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)\n<asynchronous suspension>\n#54     _rootRun (dart:async/zone.dart:1124:13)\n#55     _CustomZone.run (dart:async/zone.dart:1021:19)\n#56     _runZoned (dart:async/zone.dart:1516:10)\n#57     runZoned (dart:async/zone.dart:1463:12)\n#58     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)\n<asynchronous suspension>\n#59     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)\n<asynchronous suspension>\n#60     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)\n#61     new Future.sync (dart:async/future.dart:224:31)\n#62     CommandRunner.run (package:args/command_runner.dart:112:14)\n#63     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)\n#64     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)\n<asynchronous suspension>\n#65     _rootRun (dart:async/zone.dart:1124:13)\n#66     _CustomZone.run (dart:async/zone.dart:1021:19)\n#67     _runZoned (dart:async/zone.dart:1516:10)\n#68     runZoned (dart:async/zone.dart:1500:12)\n#69     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)\n<asynchronous suspension>\n#70     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)\n<asynchronous suspension>\n#71     _rootRun (dart:async/zone.dart:1124:13)\n#72     _CustomZone.run (dart:async/zone.dart:1021:19)\n#73     _runZoned (dart:async/zone.dart:1516:10)\n#74     runZoned (dart:async/zone.dart:1463:12)\n#75     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)\n<asynchronous suspension>\n#76     runInContext (package:flutter_tools/src/context_runner.dart:58:24)\n<asynchronous suspension>\n#77     run (package:flutter_tools/runner.dart:50:10)\n#78     main (package:flutter_tools/executable.dart:65:9)\n<asynchronous suspension>\n#79     main (file:///Users/jonahwilliams/Documents/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)\n#80     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)\n#81     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)\n"]]
```

**Comment by jakemac53** [comment]
I can't create a repro for this - I think it had something to do with some flutter specific setup which is no longer used? Going to close as assumed stale for now.
