### ISSUE TITLE
Invalid AssetGraph after commenting/uncommenting re-export

### ISSUE THREAD

**Issue by yury-yufimov** [dart-lang/build#2452]
Versions:
Dart VM version: 2.5.0 (Fri Sep 6 20:39:27 2019 +0200) on "macos_x64"
angular: 5.3.1
build_modules: 2.5.0
build_runner: 1.7.0
build_web_compilers: 2.4.0
webdev: 2.5.0
build_runner_core: 4.0.0

We've encountered following error while performing refactoring: 
when you make a mistake in imports, obviously, build fails. 
But in some cases build can't succeed even after you return code to initial state!

In particular, this happens when you have several entry points in library you depend on, and that entry points share same (transitive) imported component.

There is test project:
https://github.com/yury-yufimov/asset_graph_issue/blob/master/asset_graph_test/README.md

for reproduce you can
1. start `pub run webdev serve` in asset_graph_test
2. comment re-export in `input_comps/lib/text_input.dart`
3. Uncomment it

Error:
```
[SEVERE]build_web_compilers:ddc on package:input_comps/select.template.ddc.module: Error compiling dartdevc module:input_comps|lib/select.template.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/local/Cellar/dart/2.5.0/libexec/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/input_comps/select.template.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/logging/logging.ddc.dill=packages/logging/logging --summary=packages/path/path.ddc.dill=packages/path/path --summary=packages/stack_trace/src/chain.ddc.dill=packages/stack_trace/src/chain --summary=packages/meta/dart2js.ddc.dill=packages/meta/dart2js --summary=packages/angular/src/core/change_detection/change_detection.ddc.dill=packages/angular/src/core/change_detection/change_detection --summary=packages/angular/src/core/application_tokens.ddc.dill=packages/angular/src/core/application_tokens --summary=packages/angular/core.ddc.dill=packages/angular/core --summary=packages/angular/di.ddc.dill=packages/angular/di --summary=packages/angular/src/core/change_detection/change_detection.template.ddc.dill=packages/angular/src/core/change_detection/change_detection.template --summary=packages/angular/di.template.ddc.dill=packages/angular/di.template --summary=packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=packages/intl/intl.ddc.dill=packages/intl/intl --summary=packages/angular/src/core/application_tokens.template.ddc.dill=packages/angular/src/core/application_tokens.template --summary=packages/angular/core.template.ddc.dill=packages/angular/core.template --summary=packages/js/js_util.ddc.dill=packages/js/js_util --summary=packages/js/js.ddc.dill=packages/js/js --summary=packages/angular/src/bootstrap/modules.ddc.dill=packages/angular/src/bootstrap/modules --summary=packages/angular/angular.ddc.dill=packages/angular/angular --summary=packages/input_comps/src/text_input/text_input.ddc.dill=packages/input_comps/src/text_input/text_input --summary=packages/angular/src/bootstrap/run.template.ddc.dill=packages/angular/src/bootstrap/run.template --summary=packages/angular/angular.template.ddc.dill=packages/angular/angular.template --summary=packages/input_comps/src/text_input/text_input.template.ddc.dill=packages/input_comps/src/text_input/text_input.template --summary=packages/input_comps/src/select/select.ddc.dill=packages/input_comps/src/select/select --summary=packages/input_comps/select.ddc.dill=packages/input_comps/select --packages=file:///var/folders/rz/w8mxl36j3zd2m5dk8rz49nfn3zj2lp/T/kernel_builder_F5j95w/.packages --module-name=packages/input_comps/select.template --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/local/Cellar/dart/2.5.0/libexec/lib/libraries.json package:input_comps/select.template.dart package:input_comps/src/select/select.template.dart
    dart --version: 2.5.0 (Fri Sep 6 20:39:27 2019 +0200) on "macos_x64"

Bad state: Could not find module name for library "#lib1" from component "null".
#0      ProgramCompiler.libraryToModule (package:dev_compiler/src/kernel/compiler.dart:392:7)
#1      SharedCompiler.emitImportsAndExtensionSymbols (package:dev_compiler/src/compiler/shared_compiler.dart:449:27)
#2      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:334:5)
#3      _compile (package:dev_compiler/src/kernel/command.dart:366:27)
<asynchronous suspension>
#4      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#5      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#6      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#12     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#18     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jakemac53** [comment]
This looks like probably a frontend compiler bug, @jensjoha can you take a look?
