### ISSUE TITLE
build_web_compilers 2.5.0 does not require Dart 2.5.0 in pubspec.yaml, but should

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#2464]
build_web_compilers 2.5.0 was just released and has started causing build failures in projects that are still using a Dart SDK version <2.5.0:

An example of the build failures:
```
[SEVERE] build_web_compilers:ddc on package:fluri/fluri.ddc.module:
Error creating fluri|lib/fluri.ddc.dill
Error creating kernel summary for module:fluri|lib/fluri.ddc.dill

Response:--dart-sdk-summary=file:///usr/local/Cellar/dart/2.4.1/libexec/lib/_internal/ddc_sdk.dill --output=/private/var/folders/vb/k8ccjw095q16jrwktw31ctmm0000gn/T/scratch_spacezDfcoe/packages/fluri/fluri.ddc.dill --packages-file=file:///var/folders/vb/k8ccjw095q16jrwktw31ctmm0000gn/T/kernel_builder_TNt2dG/.packages --multi-root-scheme=org-dartlang-app --exclude-non-sources --summary-only --target=ddc --libraries-file=file:///usr/local/Cellar/dart/2.4.1/libexec/lib/libraries.json --reuse-compiler-result --use-incremental-compiler --used-inputs=/var/folders/vb/k8ccjw095q16jrwktw31ctmm0000gn/T/kernel_builder_ezioKq/used_inputs.txt --source=package:fluri/fluri.dart
FormatException: Could not find an option named "used-inputs".
#0      Parser.validate (package:args/src/parser.dart:261:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:250:7)
#2      Parser.parse (package:args/src/parser.dart:90:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:307:45)
#4      computeKernel (file:///b/s/w/ir/cache/builder/sdk/utils/bazel/kernel_worker.dart:157:38)
<asynchronous suspension>
#5      KernelWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/utils/bazel/kernel_worker.dart:58:26)
<asynchronous suspension>
#6      AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#12     main (file:///b/s/w/ir/cache/builder/sdk/utils/bazel/kernel_worker.dart:35:30)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

From what I can tell this is due to https://github.com/dart-lang/build/pull/2458

This can be worked around by either of these steps:
- Upgrading to Dart 2.5.0
- Downgrading to build_web_compilers 2.4.1

---

Unfortunately, I think a patch release of build_web_compilers that raises the minimum Dart SDK range _alone_ will still leave us in a scenario where projects on Dart 2.4 install the problematic build_web_compilers 2.5.0. Would it be possible to revert the change first in a patch version and then re-add it in another patch release with the appropriate SDK range?

@jakemac53

**Comment by jakemac53** [comment]
Gah! thanks.

We will publish a new release which ignores the option, and then another one which requires the latest sdk and respects the optoin.

**Comment by jakemac53** [comment]
Ok, versions of build_modules and build_web_compilers have been published so a `pub upgrade` should now give a working version for the current sdk

**Comment by evanweible-wf** [comment]
@jakemac53 thanks for the quick response!
