### ISSUE TITLE
"Bad state: unable to start build daemon" failures on travis

### ISSUE THREAD

**Issue by jacob314** [dart-lang/build#2651]
Repro steps:
Run travis tests for package:devtools.
Flakes almost 50% of the time running DevTools tests run on travis. Restarting the jobs usually fixes the issue.
Example bad run:
https://travis-ci.org/github/flutter/devtools/jobs/661698495

```
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)
<asynchronous suspension>
#2      BuildDaemonCreator._connectClient (package:flutter_tools/src/build_runner/web_compilation_delegate.dart:240:30)
<asynchronous suspension>
#3      BuildDaemonCreator.startBuildDaemon (package:flutter_tools/src/build_runner/web_compilation_delegate.dart:141:46)
#4      BuildRunnerWebCompilationProxy.initialize (package:flutter_tools/src/build_runner/web_compilation_delegate.dart:46:71)
#5      _FlutterTestRunnerImpl.runTests (package:flutter_tools/src/test/runner.dart:114:53)
#6      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:247:41)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:716:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:613:33)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:603:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#21     _rootRun (dart:async/zone.dart:1126:13)
#22     _CustomZone.run (dart:async/zone.dart:1023:19)
#23     _runZoned (dart:async/zone.dart:1518:10)
#24     runZoned (dart:async/zone.dart:1465:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:112:14)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1502:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     run.<anonymous closure> (package:flutter_tools/runner.dart)
#38     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:69:18)
<asynchronous suspension>
#39     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#41     _rootRun (dart:async/zone.dart:1126:13)
#42     _CustomZone.run (dart:async/zone.dart:1023:19)
#43     _runZoned (dart:async/zone.dart:1518:10)
#44     runZoned (dart:async/zone.dart:1465:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#46     runInContext (package:flutter_tools/src/context_runner.dart:72:24)
#47     run (package:flutter_tools/runner.dart:48:10)
#48     main (package:flutter_tools/executable.dart:69:9)
#49     main (file:///Users/travis/build/flutter/devtools/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by jacob314** [comment]
Fyi @grouma @kenzieschmoll

**Comment by jakemac53** [comment]
closing as assumed stale
