### ISSUE TITLE
NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'

### ISSUE THREAD

**Issue by rayk** [dart-lang/build#2724]
**The Error:**

```bash
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool
dart:core                                                              _SyncIterable.iterator
package:package_config/src/package_config_impl.dart 26:36              new SimplePackageConfig
package:package_config/src/package_config_json.dart 213:10             parsePackageConfigJson
package:package_config/src/package_config_json.dart 45:10              parsePackageConfigBytes
package:package_config/src/package_config_io.dart 117:10               readPackageConfigJsonFile
package:package_config/src/discovery.dart 109:18                       findPackagConfigInDirectory
package:package_config/src/discovery.dart 44:31                        findPackageConfig
package:package_config/package_config.dart 114:5                       findPackageConfig
package:build_runner_core/src/package_graph/package_graph.dart 74:15   PackageGraph.forPath
package:build_runner_core/src/package_graph/package_graph.dart 110:20  PackageGraph.forThisPackage
package:build_runner/src/entrypoint/run.dart 22:64                     run
.dart_tool/build/entrypoint/build.dart 38:22                           main

pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:362:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:239:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:797:18)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Trigger By:**

```flutter pub run build_runner build --delete-conflicting-outputs -v```
The same outcome is seen with:
```flutter pub run build_runner build -v```

**The Environment**

```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-AU)
    • Flutter version 1.19.0-4.1.pre at /Users/rayk/devlibs/flutter
    • Framework revision f994b76974 (29 hours ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rayk/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/rayk/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/rayk/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Users/rayk/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7846.93

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Nexus 6P   • CVH7N15A17000610 • android-arm64  • Android 8.1.0 (API 27)
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.97
```

```
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Licensed to Ray King
Subscription is active until November 9, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: dart.server.additional.arguments=--enable-completion-model, debugger.watches.in.variables=false
Non-Bundled Plugins: BrowseWordAtCaret, BunyanConsole, Dummy Text Generator, Key Promoter X, Shifter, String Manipulation, TabSwitch, awesome.console, com.fwdekker.randomness, com.giancarlocode.built-value-snippets, com.github.leomillon.uuidgenerator, com.github.lppedd.idea-conventional-commit, com.github.novotnyr.jwt-intellij-plugin, Time Convertor Plugin, com.dubreuia, com.godwin.json.parser, com.herbert.george.dart.extensions, com.herbert.george.flutter-snippets, com.marlboro.gitbar, io.github.xusida.idea.plugins.formatyaml, launch-url-from-string, com.ivanovych666.intellij.plugin.jsonsorter, com.intellij.plugins.watcher, com.wix.scss.lint, com.mallowigi, com.paperetto.dash, com.potterhsu.jsonviewer, com.shenyong.flutter.refgenerator, com.sonnk.iterm, com.wakatime.intellij.plugin, mobi.hsz.idea.gitignore, io.github.qeesung.component.HighlightBracketPair, krasa.CpuUsageIndicator, lermitage.intellij.extra.icons, com.dmarcotte.handlebars, Dart, andrasferenczi.dart-data-plugin, com.localizely.flutter-intl, io.flutter, org.bdshadow.json.serialization.generator, cz.daku.intellij.extraActions, org.jetbrains.kotlin, de.endrullis.idea.postfixtemplates, izhangzhihao.rainbow.brackets, zielu.gittoolbox, com.intellij.lang.jsgraphql, com.wix.eslint, intellij.prettierJS, org.sylfra.idea.plugins.linessorter, org.turbanov.commits.message.checker, socrates.tabshifter, zjhmale.rainbow
```

- Have seen this on two seperate environments.
- Has only started to happen since the install of _1.19.0-4.1.pre_.
- Problem was still seen after ```flutter downgrade```
- Problem was continued after ``flutter clean`` and ``flutter pub cache repair```

Any help appreciated, a bit stuck looking for workaround.

**Comment by rayk** [comment]
**Update**

- Downgrading to ```Channel stable, v1.17.3``` does not resolve the problem, but a different issue appears.

```
[INFO] Generating build script...
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _findBuilderApplications.<anonymous closure> (package:build_runner/src/build_script_generate/build_script_generate.dart:63:24)
#2      _CustomHashMap.[]= (dart:collection-patch/collection_patch.dart:278:31)
#3      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:49:12)
#4      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)
#5      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)
#6      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:57:22)
#7      stronglyConnectedComponents (package:graphs/src/strongly_connected_components.dart:76:50)
#8      _findBuilderApplications (package:build_runner/src/build_script_generate/build_script_generate.dart:59:27)
<asynchronous suspension>
#9      _generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:28:26)
#10     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
#11     generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:25:5)
#12     generateAndRun (package:build_runner/src/build_script_generate/bootstrap.dart:49:31)
<asynchronous suspension>
#13     main (file:///Users/rayk/development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/bin/build_runner.dart:87:30)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by igoriuz** [comment]
I've a similar error message. Just downgrade to build_runner 1.9.0

**Comment by rayk** [comment]
**Update**

May have located the package causing the problem, through a process of reverts and elimination so can not be sure.

By removing ```hive_generator: ^0.7.0+2```  & reverting back to ```Channel beta, 1.18.0-11.1.pre``` the problem is resolved, as to what is causing the issue within hive_generator I have not yet work this out. I am going to close this issue in favour of an [issue ](https://github.com/hivedb/hive/issues/343)over at hive.

**Comment by FakenMaster** [comment]
Duplicate of #2721
