### ISSUE TITLE
A bug in build_runner

### ISSUE THREAD

**Issue by rustkas** [dart-lang/build#2734]
Thank you for taking the time to file an issue!

Stacktrace information:
```
[SEVERE]                                                                          
[SEVERE]                                                                          
[SEVERE] You have hit a bug in build_runner                                       
[SEVERE] Please file an issue with reproduction steps at https://github.com/dart-l
ang/build/issues                                                                  
[SEVERE]                                                                          
[SEVERE]                                                                          
[SEVERE] NoSuchMethodError: Closure call with mismatched arguments: function 'Muta
blePackageTree.allPackages'                                                       
[SEVERE] Receiver: Closure: (_SyncIterator<Package>) => bool                      
[SEVERE] Tried calling: MutablePackageTree.allPackages()                          
[SEVERE] Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool    
[SEVERE] dart:core                                                                
                       _SyncIterable.iterator                                     
[SEVERE] package:package_config/src/package_config_impl.dart 26:36                
                       new SimplePackageConfig                                    
[SEVERE] package:package_config/src/package_config_json.dart 213:10               
                       parsePackageConfigJson                                     
[SEVERE] package:package_config/src/package_config_json.dart 45:10                
                       parsePackageConfigBytes                                    
[SEVERE] package:package_config/src/package_config_io.dart 117:10                 
                       readPackageConfigJsonFile                                  
[SEVERE] package:package_config/src/discovery.dart 109:18                         
                       findPackagConfigInDirectory                                
[SEVERE] package:package_config/src/discovery.dart 44:31                          
                       findPackageConfig                                          
[SEVERE] package:package_config/package_config.dart 114:5                         
                       findPackageConfig                                          
[SEVERE] package:build_runner_core/src/package_graph/package_graph.dart 74:15     
                       PackageGraph.forPath                                       
[SEVERE] package:build_runner_core/src/package_graph/package_graph.dart 110:20    
                       PackageGraph.forThisPackage                                
[SEVERE] package:build_runner/src/entrypoint/run.dart 22:64                       
                       run                                                        
[SEVERE] ..\..\02_websocket_send_data_to_the_server\client\.dart_tool\build\entryp
oint\build.dart 89:22  main                                                       
[SEVERE]                                                                          
Unhandled exception:                                                              
Bad state: Unable to start build daemon.                                          
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)              
<asynchronous suspension>                                                         
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)       
<asynchronous suspension>                                                         
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)               
#3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:26:18)      
#4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:191:24)     
#5      ServeCommand.run (package:webdev/src/command/serve_command.dart:101:27)   
<asynchronous suspension>                                                         
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)        
#7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:3
8:24)                                                                             
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:11
2:25)                                                                             
#9      new Future.sync (dart:async/future.dart:222:31)                           
#10     CommandRunner.run (package:args/command_runner.dart:112:14)               
#11     run (package:webdev/src/webdev_command_runner.dart:19:56)                 
#12     main (file:///E:/Users/tol_pc/AppData/Roaming/Pub/Cache/hosted/pub.dartlan
g.org/webdev-2.5.8/bin/webdev.dart:17:22)                                         
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:2
99:32)                                                                            
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:
168:12)                                                                           
```

* Dart SDK Version (Dart VM version: 2.9.0-14.1.beta (beta) (Tue Jun 9 10:52:57 2020 +0200) on "windows_x64")
*  (i.e. `build_runner: ^1.10.0`)
* Launch `webdev serve` stagehand web template app
* Whether you are using Windows 7
* command line issue
* Any other packages or constraints we should know about:
environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  model:
    path: ../model

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0

**Comment by rustkas** [comment]
I fix it by remove:
* .dart_tool
* pubspec.lock
* .packages
After that I use `webdev serve` again and web server start without crashes.
