### ISSUE TITLE
'flutter pub run build_runner build -v' brings exit code 1 

### ISSUE THREAD

**Issue by Kobreizhyashi** [dart-lang/build#2751]
Hi, I have few problems with my flutter app. For the first time when I try to run 'pub run build_runner build' I have a problem :  

MBP-of-meAsAUser:core meAsAUser$ flutter pub run build_runner build -v
Failed to precompile build_runner:build_runner:
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart:9:8: Error: Error when reading '../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-2.1.4/lib/graphic_chart.dart': No such file or directory
import 'package:build_daemon/graphic_chart.dart';
       ^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/options.dart:11:8: Error: Error when reading '../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-2.1.4/lib/graphic_chart.dart': No such file or directory
import 'package:build_daemon/graphic_chart.dart';
       ^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart:13:8: Error: Error when reading '../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/daemon/graphic_chart.dart': No such file or directory
import 'package:build_runner/src/daemon/graphic_chart.dart';
       ^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/daemon/daemon_builder.dart:9:8: Error: Error when reading '../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-2.1.4/lib/graphic_chart.dart': No such file or directory
import 'package:build_daemon/graphic_chart.dart';
       ^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/options.dart:136:3: Error: Type 'BuildMode' not found.
  BuildMode buildMode;
  ^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart:34:25: Error: The getter 'buildModeFlag' isn't defined for the class 'DaemonCommand'.
 - 'DaemonCommand' is from 'package:build_runner/src/entrypoint/daemon.dart' ('../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'buildModeFlag'.
    argParser.addOption(buildModeFlag,
                        ^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart:52:22: Error: The getter 'currentVersion' isn't defined for the class 'DaemonCommand'.
 - 'DaemonCommand' is from 'package:build_runner/src/entrypoint/daemon.dart' ('../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'currentVersion'.
      if (version != currentVersion) {
                     ^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart:55:40: Error: The getter 'currentVersion' isn't defined for the class 'DaemonCommand'.
 - 'DaemonCommand' is from 'package:build_runner/src/entrypoint/daemon.dart' ('../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'currentVersion'.
          ..writeln('Current Version: $currentVersion')
                                       ^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart:56:21: Error: The getter 'versionSkew' isn't defined for the class 'DaemonCommand'.
 - 'DaemonCommand' is from 'package:build_runner/src/entrypoint/daemon.dart' ('../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'versionSkew'.
          ..writeln(versionSkew);
                    ^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart:63:21: Error: The getter 'optionsSkew' isn't defined for the class 'DaemonCommand'.
 - 'DaemonCommand' is from 'package:build_runner/src/entrypoint/daemon.dart' ('../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.0/lib/src/entrypoint/daemon.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'optionsSkew'.
          ..writeln(optionsSkew);
                    ^^^^^^^^^^^
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:338:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:239:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#11     _rootRun (dart:async/zone.dart:1184:13)
#12     _CustomZone.run (dart:async/zone.dart:1077:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

HAve you ever faced the same issue ? 

I've already flutter clean, pub get up update upgrade etc.. :/ Without success.

**Comment by Kobreizhyashi** [comment]
Found the issue. flutter pub cache repair solved everything.
