### ISSUE TITLE
build_runner not working with new localization support

### ISSUE THREAD

**Issue by dalewking** [dart-lang/build#2865]
Using build_runner 1.10.3 and dart version  2.11.0-186.0.dev on MacOSX

As can be seen in the [document describing the new l10n process for flutter](https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit) the flutter tool generates a "synthetic package" containing a generated class for accessing the strings. The synthetic package is generated under .dart_tool/flutter_gen/gen_l10n.

This does not work with build_runner however. After the generation for localization trying to run build_runner gives you this error because the synthetic package does not actually have a pubspec.yaml file and you get an error like this:

```
$ flutter pub run build_runner build
Unhandled exception:
Bad state: Unable to generate package graph, no `/Users/dalewking/my_flutter/.dart_tool/flutter_gen/pubspec.yaml` found.
#0      _pubspecForPath (package:build_runner_core/src/package_graph/package_graph.dart:235:5)
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:208:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:97:33)
<asynchronous suspension>
#3      PackageGraph.forThisPackage (package:build_runner_core/src/package_graph/package_graph.dart:110:20)
#4      main (file:///usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.3/bin/build_runner.dart:27:49)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

**Comment by dalewking** [comment]
Duplicate of #2835
