### ISSUE TITLE
Failed to precompile build_runner:build_runner

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/build#3114]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
  * `Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "macos_x64"`
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * `build_runner: ^2.0.4`
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
  * `build_web_compilers: ^3.0.0`
* Whether you are using Windows, MacOSX, or Linux (if applicable)
  * macOS

```console
$ webdev serve
[SEVERE] Failed to precompile build_runner:build_runner:
[SEVERE] ../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:1600:40: Error: Getter not found: 'topLevelVariable'.
[SEVERE]       return kinds.contains(TargetKind.topLevelVariable);
[SEVERE]                                        ^^^^^^^^^^^^^^^^
[SEVERE] ../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Getter not found: 'topLevelVariable'.
[SEVERE]       case TargetKind.topLevelVariable:
[SEVERE]                       ^^^^^^^^^^^^^^^^
[SEVERE] ../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Type 'dynamic' of the case expression is not a subtype of type 'TargetKind' of this switch expression.
[SEVERE]  - 'TargetKind' is from 'package:meta/meta_meta.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/meta-1.3.0/lib/meta_meta.dart').
[SEVERE]       case TargetKind.topLevelVariable:
[SEVERE]                       ^
[SEVERE] ../../../../.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2001:13: Context: The switch expression is here.
[SEVERE]     switch (this) {
[SEVERE]             ^
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:5)
<asynchronous suspension>
#2      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:28:12)
<asynchronous suspension>
#3      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:193:18)
<asynchronous suspension>
#4      ServeCommand.run (package:webdev/src/command/serve_command.dart:102:9)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#6      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:40:12)
<asynchronous suspension>
#7      main (file:///Users/brettmorgan/.pub-cache/hosted/pub.dartlang.org/webdev-2.7.4/bin/webdev.dart:19:16)
<asynchronous suspension>
```

Probably related to: https://github.com/dart-lang/protobuf/issues/509

**Comment by domesticmouse** [comment]
Related: https://github.com/dart-lang/sdk/issues/46136

**Comment by jakemac53** [comment]
This was a bad release of analyzer, which depended on a not yet released version of meta but didn't have the version constraints right.

That meta version (1.4.0) is now released, and updating to that should fix your issue.

**Comment by bayuly94** [comment]
how to fix it ?

**Comment by jakemac53** [comment]
You should just need to `pub upgrade`, you can require the latest meta (`meta: ^1.4.0`) or the latest analyzer (`analyzer: ^1.7.0`) or both as well to ensure you get good versions.
