### ISSUE TITLE
Unhandled exception: type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by mqus** [dart-lang/build#3259]
Hi!
I try some funky stuff in my builder (https://api.dart.dev/stable/2.16.1/dart-mirrors/IsolateMirror/loadUri.html) which fails. But I sadly can't see why exactly because in trying to catch that error, build_runner also has an exception:
```
Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      generateAndRun.<anonymous closure> (package:build_runner/src/build_script_generate/bootstrap.dart:77:38)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#4      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#5      _StreamController._add (dart:async/stream_controller.dart:648:7)
#6      _StreamController.add (dart:async/stream_controller.dart:596:5)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
[+11479 ms] "flutter run" took 11,636ms.
```

I assume that this is because of the following section:

https://github.com/dart-lang/build/blob/6ccafdf77ade4003c5f9392c1215651f67e54e88/build_runner/lib/src/build_script_generate/bootstrap.dart#L75-L77 

If I read [the documentation](https://api.dart.dev/stable/2.16.1/dart-isolate/Isolate/addErrorListener.html) right (referenced in  [`spawnUri`](https://api.dart.dev/stable/2.16.1/dart-isolate/Isolate/spawnUri.html)) then `e[1]` can also be null and will not be castable into a String. 

Additionally, the docs don't say that e[0] can be `null` so this might be unnecessary (but they also don't say it can't be null).

Apart from that, is there another way to forcefully show the stacktrace, error, or really any information of the builder isolate without touching `build_runner`? I'm somewhat lost.

**Comment by jakemac53** [comment]
> If I read [the documentation](https://api.dart.dev/stable/2.16.1/dart-isolate/Isolate/addErrorListener.html) right (referenced in [`spawnUri`](https://api.dart.dev/stable/2.16.1/dart-isolate/Isolate/spawnUri.html)) then `e[1]` can also be null and will not be castable into a String.

Ya it looks like we should support a null trace here then. No idea what would cause there to be no stack trace though.... maybe a dart VM crash?

> Additionally, the docs don't say that e[0] can be `null` so this might be unnecessary (but they also don't say it can't be null).

This is allowed in non-migrated code which is why we check it.

> Apart from that, is there another way to forcefully show the stacktrace, error, or really any information of the builder isolate without touching `build_runner`? I'm somewhat lost.

You can directly run the generated script, it should live at `.dart_tool/build/entrypoint/build.dart`. Just run that directly (treat it the same way you would `build_runner`),  you can also hook in a debugger if you like that way.

> I try some funky stuff in my builder (using https://api.dart.dev/stable/2.16.1/dart-mirrors/IsolateMirror/loadUri.html) which fails (probably a crash). But I sadly can't see why exactly because in trying to catch that error, build_runner also has an exception:

Note that doing this will circumvent any invalidation that build_runner is doing. So if the plugin code itself changes, build_runner won't know about it and invalidate the things built with that plugin. So it will result in stale/invalid builds essentially.

**Comment by mqus** [comment]
> Ya it looks like we should support a null trace here then. No idea what would cause there to be no stack trace though.... maybe a dart VM crash?
> 

I think so, yes.

> You can directly run the generated script, it should live at `.dart_tool/build/entrypoint/build.dart`. Just run that directly (treat it the same way you would `build_runner`), you can also hook in a debugger if you like that way.

Thanks! I'll try that.

> Note that doing this will circumvent any invalidation that build_runner is doing. So if the plugin code itself changes, build_runner won't know about it and invalidate the things built with that plugin. So it will result in stale/invalid builds essentially.

Yeah... the idea was that the user of the builder imports the floor generator and another library which includes the plugin and then "uses" the Plugin by annotating something like

```dart
@Database(plugins:[otherlib.FooPlugin])
class MyDatabase{ ... }
```
which will then cause the floor generator to dynamically load the plugin and use it via an API Interface.

In that case, since the plugin is also imported, there is *some* stability there and the rest of the invalidation cases could then be adressed with documentation.

But as mentioned, I am still trying. One thing I have to make sure of e.g. is that `otherlib` is actually reachable from the builder...

But it's more of a weekend project so it's likely I'll lose interest sooner or later :D
