### ISSUE TITLE
Build Runner Error (may be about enhanced enums)-> RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by phcs971** [dart-lang/build#3310]
I'm getting an error when running 

`flutter packages pub run build_runner watch --delete-conflicting-outputs`

It also happens on `build_runner build` and if I remove the `--delete-conflicting-outputs`

```
[SEVERE] mobx_codegen:mobx_generator on lib/app/enums/marital_status_enum.dart:

RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      ElementWalker.getConstructor (package:analyzer/src/generated/declaration_resolver.dart:159:21)
#2      ResolutionVisitor.visitConstructorDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:283:54)
#3      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2512:15)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#5      ResolutionVisitor.visitEnumDeclaration.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:415:22)
#6      ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1413:8)
#7      ResolutionVisitor.visitEnumDeclaration.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:408:7)
#8      ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1402:8)
#9      ResolutionVisitor.visitEnumDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:407:5)
#10     EnumDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3405:50)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2105:21)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:765:10)
#14     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#15     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:752:10)
#16     LibraryAnalyzer._parseAndResolve.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:597:7)
#17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#18     LibraryAnalyzer._parseAndResolve (package:analyzer/src/dart/analysis/library_analyzer.dart:596:11)
#19     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:105:17)
#20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1447:11)
#21     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1424:20)
#23     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1485:26)
#24     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1097:20)
#25     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2127:24)
<asynchronous suspension>
```

The file it reports contained the following code:

```dart
enum MaritalStatus {
  Single("União Estável"),
  Married("Divorciado(a)"),
  Widowed("Casado(a)"),
  Divorced("Solteiro(a)"),
  CommonLawMarriage("Viúvo(a)");

  final String text;

  const MaritalStatus(this.text);
}
```

Once it started happening right around when I started using enhanced enums, I tried downgrading it to normal enums (which worked with the build_runner for more than a year), but the error persisted.

Current content: 

```dart
enum MaritalStatus { Single, Married, Widowed, Divorced, CommonLawMarriage }

extension MaritalStatusExtension on MaritalStatus {
  String get text {
    switch (this) {
      case MaritalStatus.CommonLawMarriage:
        return "União Estável";
      case MaritalStatus.Divorced:
        return "Divorciado(a)";
      case MaritalStatus.Married:
        return "Casado(a)";
      case MaritalStatus.Single:
        return "Solteiro(a)";
      case MaritalStatus.Widowed:
        return "Viúvo(a)";
    }
  }
}
```

After the [SEVERE] report it goes on a loop like the following:
```
[INFO] 23.1s elapsed, 12/28 actions completed.
[INFO] 24.2s elapsed, 12/28 actions completed.
[INFO] 25.2s elapsed, 12/28 actions completed.
[INFO] 26.3s elapsed, 12/28 actions completed.
[WARNING] No actions completed for 15.0s, waiting on:
  - mobx_codegen:mobx_generator on lib/app/enums/invoice_status_enum.dart
  - mobx_codegen:mobx_generator on lib/app/enums/social_network_enum.dart
  - mobx_codegen:mobx_generator on lib/app/enums/status_enum.dart
  - mobx_codegen:mobx_generator on lib/app/enums/credit_cart_type_enum.dart
  - mobx_codegen:mobx_generator on lib/app/app_widget.dart
  .. and 11 more

[INFO] 28.1s elapsed, 12/28 actions completed.
[INFO] 29.1s elapsed, 12/28 actions completed.
```

dart --version
```
Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "macos_x64"
```

Packages:
- build_runner 2.1.11
- build_runner_core 7.2.3

Builders:
- mobx_codegen: 2.0.7

**Comment by phcs971** [comment]
I also created the same issue in the mobx_codegen repository: https://github.com/mobxjs/mobx.dart/issues/821

**Comment by jakemac53** [comment]
This looks like an analyzer issue, can you confirm you are on the latest analyzer before we move this issue to the SDK?

You can do a `dart pub upgrade` and it should show next to the analyzer if there is a newer version than what you have.

**Comment by phcs971** [comment]
> This looks like an analyzer issue, can you confirm you are on the latest analyzer before we move this issue to the SDK?
> 
> You can do a `dart pub upgrade` and it should show next to the analyzer if there is a newer version than what you have.

flutter pub upgrade worked, thank you!
