### ISSUE TITLE
ObjectBox core dynamic library has unsupported version 0.17.0, expected ^0.18.0

### ISSUE THREAD

**Issue by bishwos** [dart-lang/build#3453]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`):`2.19.1(stable)`
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`): `1.7.2`
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do:`build_runner 2.3.3`
* Whether you are using Windows, MacOSX, or Linux (if applicable): `MacOSX`

----
After upgrading to version 1.7.2, when I run using `flutter run` and select emulator it gives throws the error.
```
Running Gradle task 'assembleDebug'...                             19.8s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/flutter (11805): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: 
Loaded ObjectBox core dynamic library has unsupported version 0.17.0, expected ^0.18.0
E/flutter (11805): #0      loadObjectBoxLib (package:objectbox/src/native/bindings/bindings.dart:110:5)
E/flutter (11805): #1      C (package:objectbox/src/native/bindings/bindings.dart:119:27)
E/flutter (11805): #2      C (package:objectbox/src/native/bindings/bindings.dart)
E/flutter (11805): #3      new Model (package:objectbox/src/native/model.dart:19:31)
E/flutter (11805): #4      new Store (package:objectbox/src/native/store.dart:175:21)
E/flutter (11805): #5      openStore (package:chatapp/services/store/objectbox.g.dart:418:5)
E/flutter (11805): <asynchronous suspension>
E/flutter (11805): #6      ObjectBox.init (package:chatapp/services/store/ObjectBox.dart:23:13)
E/flutter (11805): <asynchronous suspension>
E/flutter (11805): #7      main (package:chatapp/main.dart:44:3)
E/flutter (11805): <asynchronous suspension>
E/flutter (11805): 
```

**Comment by jakemac53** [comment]
This looks like a flutter issue, we can't transfer issues across repos so can you re-file it on flutter/flutter?
