### ISSUE TITLE
PathNotFoundException: Cannot delete file...

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/build#3464]
Versions
* dart: `Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "macos_arm64"`
* package: `build_runner: 2.3.3`
* builder: `json_serializable: 6.6.1`
* os: `macOS`

Command
```console
flutter pub run build_runner build --delete-conflicting-outputs
```

Console output
```console
[INFO] Generating build script...
[INFO] Generating build script completed, took 161ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 42ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.5s

[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds....


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


PathNotFoundException: Cannot delete file, path = '/Users/rexios/repos/[REDACTED PROJECT NAME]/example/ios/.symlinks/plugins/[REDACTED PROJECT NAME]/lib/src/model/[REDACTED FILE NAME].g.dart' (OS Error: No such file or directory, errno = 2)
dart:async                                                           _rootRunUnary
package:build_runner_core/src/asset/file_based.dart 106:9            FileBasedAssetWriter.delete.<fn>
package:pool/pool.dart 127:14                                        Pool.withResource
dart:async                                                           Future.wait.<fn>
package:build_runner_core/src/generate/build_definition.dart 427:7   _Loader._cleanupOldOutputs.<fn>
package:build_runner_core/src/logging/logging.dart 25:18             logTimedAsync
package:build_runner_core/src/generate/build_definition.dart 424:5   _Loader._cleanupOldOutputs
package:build_runner_core/src/generate/build_definition.dart 235:36  _Loader.prepareWorkspace
package:build_runner_core/src/generate/build_impl.dart 114:27        BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:26       BuildRunner.create
package:build_runner/src/generate/build.dart 109:17                  build
package:build_runner/src/entrypoint/build.dart 35:18                 BuildCommand._run
package:args/command_runner.dart 212:13                              CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                   run
.dart_tool/build/entrypoint/build.dart 34:16                         main
```

**Comment by Rexios80** [comment]
Setting `followLinks` to `false` here seems to fix the issue, but that might have other consequences

https://github.com/dart-lang/build/blob/3aecb6912d2d6a165cca793afa27fba3ed502301/build_runner_core/lib/src/asset/file_based.dart#L53

**Comment by jakemac53** [comment]
Related to https://github.com/google/json_serializable.dart/issues/1285 probably? I think this is a case where there are symlinks back to the main project from an example directory.

**Comment by corgivn** [comment]
Any update on this issue?

**Comment by jakemac53** [comment]
I wonder if we just shouldn't follow symlinks? What is the exact use case for symlinks here?

**Comment by sbatezat** [comment]
I think I've got the same issue, if it's not, please tell me and I will post a new issue.
Here's my stacktrace for flutter pub run build_runner build --verbose

```
[   +6 ms] executing: [/sdks/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] executing: [/sdks/flutter/] git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[  +97 ms] Exit code 0 from: git tag --points-at f468f3366c26a5092eb964a230ce7892fda8f2f8
[        ] 3.10.6
[   +3 ms] executing: [/sdks/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[        ] executing: [/sdks/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +3 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] fatal: HEAD does not point to a branch
[   +6 ms] executing: uname -m
[  +68 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +26 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +175 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +114 ms] executing: [/builds/dsir/groupemob_factory-dsir/05937/coeur-incident-ferroviaire-mobile/packages/domain/] /sdks/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run build_runner build --verbose
FINE: Pub 3.0.6
MSG : Deprecated. Use `dart run` instead.
FINE: Package Config up to date.
FINE: Package Config up to date.
MSG : Building package executable...
IO  : Created temp directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB
MSG : Built build_runner:build_runner.
IO  : Renaming "./.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp" to "./.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot".
IO  : Deleting directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB.
ERR : Cannot rename file to './.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot', path = './.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp' (OS Error: No such file or directory, errno = 2)
FINE: Exception type: PathNotFoundException
FINE: dart:io                                              _File.renameSync
    | package:pub/src/io.dart 534:14                       renameFile
    | package:pub/src/dart.dart 162:7                      precompile
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.catchError
    | package:pub/src/utils.dart 150:21                    waitAndPrintErrors.<fn>
    | dart:async                                           Future.wait
    | package:pub/src/utils.dart 148:17                    waitAndPrintErrors
    | package:pub/src/entrypoint.dart 494:14               Entrypoint.precompileExecutable.<fn>
    | package:pub/src/log.dart 438:18                      progress
    | package:pub/src/entrypoint.dart 492:15               Entrypoint.precompileExecutable
    | package:pub/src/command/run.dart 106:26              RunCommand.runProtected.<fn>.<fn>
    | package:pub/src/log.dart 421:32                      errorsOnlyUnlessTerminal
    | package:pub/src/command/run.dart 105:38              RunCommand.runProtected.<fn>
    | package:pub/src/executable.dart 97:22                runExecutable
    | ===== asynchronous gap ===========================
    | dart:async                                           _CustomZone.registerUnaryCallback
    | package:pub/src/executable.dart 93:5                 runExecutable
    | package:pub/src/command/run.dart 100:26              RunCommand.runProtected
    | ===== asynchronous gap ===========================
    | dart:async                                           _CustomZone.registerUnaryCallback
    | package:pub/src/command/run.dart 61:7                RunCommand.runProtected
    | package:pub/src/command.dart 199:21                  PubCommand.run.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 113:12                    captureErrors.wrappedCallback
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 126:11                    captureErrors
    | package:pub/src/command.dart 198:13                  PubCommand.run
    | package:args/command_runner.dart 212:27              CommandRunner.runCommand
    | package:dartdev/dartdev.dart 226:30                  DartdevRunner.runCommand
    | package:args/command_runner.dart [122](https://gitlab-repo-res.apps.eul.sncf.fr/dsir/groupemob_factory-dsir/05937/coeur-incident-ferroviaire-mobile/-/jobs/1189712#L122):25              CommandRunner.run.<fn>
    | dart:async                                           new Future.sync
    | package:args/command_runner.dart 122:14              CommandRunner.run
    | package:dartdev/dartdev.dart 58:29                   runDartdev
    | /b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
FINE: Building package executable finished (12.096s).
---- Log transcript ----
FINE: Pub 3.0.6
MSG : Deprecated. Use `dart run` instead.
FINE: Package Config up to date.
FINE: Package Config up to date.
MSG : Building package executable...
IO  : Created temp directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB
MSG : Built build_runner:build_runner.
IO  : Renaming "./.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp" to "./.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot".
IO  : Deleting directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB.
ERR : Cannot rename file to './.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot', path = './.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp' (OS Error: No such file or directory, errno = 2)
FINE: Exception type: PathNotFoundException
FINE: dart:io                                              _File.renameSync
    | package:pub/src/io.dart 534:14                       renameFile
    | package:pub/src/dart.dart 162:7                      precompile
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.catchError
    | package:pub/src/utils.dart 150:21                    waitAndPrintErrors.<fn>
    | dart:async                                           Future.wait
    | package:pub/src/utils.dart 148:17                    waitAndPrintErrors
    | package:pub/src/entrypoint.dart 494:14               Entrypoint.precompileExecutable.<fn>
    | package:pub/src/log.dart 438:18                      progress
    | package:pub/src/entrypoint.dart 492:15               Entrypoint.precompileExecutable
    | package:pub/src/command/run.dart 106:26              RunCommand.runProtected.<fn>.<fn>
    | package:pub/src/log.dart 421:32                      errorsOnlyUnlessTerminal
    | package:pub/src/command/run.dart 105:38              RunCommand.runProtected.<fn>
    | package:pub/src/executable.dart 97:22                runExecutable
    | ===== asynchronous gap ===========================
    | dart:async                                           _CustomZone.registerUnaryCallback
    | package:pub/src/executable.dart 93:5                 runExecutable
    | package:pub/src/command/run.dart 100:26              RunCommand.runProtected
    | ===== asynchronous gap ===========================
    | dart:async                                           _CustomZone.registerUnaryCallback
    | package:pub/src/command/run.dart 61:7                RunCommand.runProtected
    | package:pub/src/command.dart 199:21                  PubCommand.run.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 113:12                    captureErrors.wrappedCallback
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart [126](https://gitlab-repo-res.apps.eul.sncf.fr/dsir/groupemob_factory-dsir/05937/coeur-incident-ferroviaire-mobile/-/jobs/1189712#L126):11                    captureErrors
    | package:pub/src/command.dart 198:13                  PubCommand.run
    | package:args/command_runner.dart 212:27              CommandRunner.runCommand
    | package:dartdev/dartdev.dart 226:30                  DartdevRunner.runCommand
    | package:args/command_runner.dart 122:25              CommandRunner.run.<fn>
    | dart:async                                           new Future.sync
    | package:args/command_runner.dart 122:14              CommandRunner.run
    | package:dartdev/dartdev.dart 58:29                   runDartdev
    | /b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
FINE: Building package executable finished (12.096s).
---- End log transcript ----
IO  : Writing 11135 characters to text file /root/.pub-cache/log/pub_log.txt.
MSG : Logs written to /root/.pub-cache/log/pub_log.txt.
[+13994 ms] pub failed
            command: "/sdks/flutter/bin/cache/dart-sdk/bin/dart pub --suppress-analytics run build_runner build --verbose"
            pub env: {
              "FLUTTER_ROOT": "/sdks/flutter",
              "PUB_ENVIRONMENT": "flutter_bot:flutter_cli:forward",
            }
            exit code: 66
[  +13 ms] "flutter run" took 14,305ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
           <asynchronous suspension>
           #2      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:530:5)
           <asynchronous suspension>
           #3      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:122:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:[133](https://gitlab-repo-res.apps.eul.sncf.fr/dsir/groupemob_factory-dsir/05937/coeur-incident-ferroviaire-mobile/-/jobs/1189712#L133)6:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:[150](https://gitlab-repo-res.apps.eul.sncf.fr/dsir/groupemob_factory-dsir/05937/coeur-incident-ferroviaire-mobile/-/jobs/1189712#L150):19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:[212](https://gitlab-repo-res.apps.eul.sncf.fr/dsir/groupemob_factory-dsir/05937/coeur-incident-ferroviaire-mobile/-/jobs/1189712#L212):13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:[244](https://gitlab-repo-res.apps.eul.sncf.fr/dsir/groupemob_factory-dsir/05937/coeur-incident-ferroviaire-mobile/-/jobs/1189712#L244):5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
[  +74 ms] ensureAnalyticsSent: 1ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 66
```

It's easy to understand.
First, it's moving a file from ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB

`IO  : Renaming "./.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp" to "./.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot".`

Before it's ended, it's removing it :

`IO  : Deleting directory ./.dart_tool/pub/incremental/build_runner/tmpIFZKLB.
`

We then have obviously this error, telling us we cannot move a file which doesn't exists anymore.

ERR : Cannot rename file to './.dart_tool/pub/bin/build_runner/build_runner.dart-3.0.6.snapshot', path = './.dart_tool/pub/incremental/build_runner/tmpIFZKLB/build_runner.dart.incremental.dill.temp' (OS Error: No such file or directory, errno = 2)

**Comment by jakemac53** [comment]
@sbatezat that looks like a different issue - it's actually a pub issue when compiling `build_runner` itself, so I would file the issue there (https://github.com/dart-lang/pub/issues/new?template=2-BUG.md). That might end up being an SDK (core libs) issue or something but I would start by filing it on pub.

**Comment by wujek-srujek** [comment]
@jakemac53 I'm running into the same issue, I got the error now 7 times in a row (normally I get it once and the next run works). The symlinks are not something we create ourselves, they are created automatically for the iOS part of a Flutter plugin, within the iOS part of the 'example'.

**Comment by jakemac53** [comment]
The easiest solution here is probably just excluding that symlinks dir entirely from the build? Try putting this in your `build.yaml` file:

```yaml
targets:
  $default:
    sources:
      exclude:
        # Example that excludes intellij's swap files
        - example/ios/.symlinks
```

Related to https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-fix-assetnotfoundexceptions-for-swap-files

**Comment by Rexios80** [comment]
Do we actually want this to be closed? I reproduced this yesterday.

**Comment by jakemac53** [comment]
@Rexios80 did you exclude your symlink directories per https://github.com/dart-lang/build/issues/3464#issuecomment-1699238702?

**Comment by Rexios80** [comment]
That should fix it, but can't that just happen by default?

**Comment by jakemac53** [comment]
We only support the [pub package layout](https://dart.dev/tools/pub/package-layout) conventions by default today - we have to choose some default setup that makes sense and that is the standard one.

I don't know enough about flutter to know if there are additional defaults we should be adding. Everything we add does come with a cost for _all_ users (all globs are matched against all files), so we only want to default to something we think the vast majority of users need.

**Comment by wujek-srujek** [comment]
I have a question - is there some kind of a race condition in the logic? How is it that (without the exclusions mentioned above) it sometimes fails, but then I retry (sometimes more than 1 retry is needed) and it works?

**Comment by jakemac53** [comment]
Yeah, almost certainly a race condition in there.

**Comment by wujek-srujek** [comment]
In this case, shouldn't the race condition have a bug issued?

**Comment by jakemac53** [comment]
It only occurs for an unsupported situation - symlinks to files in the same project
