### ISSUE TITLE
Get error on flutter pub run build_runner build --delete-conflicting-outputs

### ISSUE THREAD

**Issue by vadimlukutin** [dart-lang/build#3550]
Null check operator used on a null value
#0      PackageGraph.forPath.<anonymous closure> (package:build_runner_core/src/package_graph/package_graph.dart:110:72)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#3      List.addAll (dart:core-patch/growable_array.dart:325:17)
#4      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:110:12)
<asynchronous suspension>
#5      main (file:///home/vadimlukutin/.pub-cache/hosted/pub.dev/build_runner-2.4.6/bin/build_runner.dart:27:30)
<asynchronous suspension>

**Comment by vadimlukutin** [comment]
helped run command
> flutter gen-l10n

**Comment by jakemac53** [comment]
Can you try running a `flutter pub get` and then re-running the same command? I think your package config and pubspec might be out of sync.

**Comment by tayadepritam0** [comment]
hello my friend 

try adding packages first
json_annotation 
json_serializable
build_runner

click on pub get 
then open terminal and run command
flutter pub run build_runner build --delete-conflicting-outputs
