### ISSUE TITLE
Type cast issue (CheckedFromJsonException) when trying to use FlutterGen

### ISSUE THREAD

**Issue by kevan-mtl** [dart-lang/build#3611]
hi everyone,

I'm trying to use the [Flutter Gen](https://pub.dev/packages/flutter_gen) package in my app and I get a weird builder_runner issue...

To start, here is my Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.5.1 22G90 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.81.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

Here is the error I run into when trying to run `dart run build_runner build --delete-conflicting-outputs`:

```
flashcard_app_frontend:
[INFO] Generating build script...
[INFO] Generating build script completed, took 174ms

[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 646ms

FlutterGen v5.3.2 Loading ... pubspec.yaml


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


CheckedFromJsonException
Could not create `FlutterGenAssets`.
There is a problem with "outputs".
type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast


package:json_annotation/src/checked_helpers.dart 91:5                   $checkedConvert
package:json_annotation/src/checked_helpers.dart 28:7                   $checkedCreate.checkedConvert
package:flutter_gen_core/settings/pubspec.g.dart 129:35                 _$FlutterGenAssetsFromJson.<fn>
package:json_annotation/src/checked_helpers.dart 33:22                  $checkedCreate.<fn>
package:json_annotation/src/checked_helpers.dart 51:23                  $checkedNew
package:json_annotation/src/checked_helpers.dart 30:10                  $checkedCreate
package:flutter_gen_core/settings/pubspec.g.dart 116:58                 _$FlutterGenAssetsFromJson
package:flutter_gen_core/settings/pubspec.dart 134:7                    new FlutterGenAssets.fromJson
package:flutter_gen_core/settings/pubspec.g.dart 84:49                  _$FlutterGenFromJson.<fn>.<fn>
package:json_annotation/src/checked_helpers.dart 87:20                  $checkedConvert
package:json_annotation/src/checked_helpers.dart 28:7                   $checkedCreate.checkedConvert
package:flutter_gen_core/settings/pubspec.g.dart 83:34                  _$FlutterGenFromJson.<fn>
package:json_annotation/src/checked_helpers.dart 33:22                  $checkedCreate.<fn>
package:json_annotation/src/checked_helpers.dart 51:23                  $checkedNew
package:json_annotation/src/checked_helpers.dart 30:10                  $checkedCreate
package:flutter_gen_core/settings/pubspec.g.dart 65:46                  _$FlutterGenFromJson
package:flutter_gen_core/settings/pubspec.dart 82:44                    new FlutterGen.fromJson
package:flutter_gen_core/settings/pubspec.g.dart 20:48                  _$PubspecFromJson.<fn>.<fn>
package:json_annotation/src/checked_helpers.dart 87:20                  $checkedConvert
package:json_annotation/src/checked_helpers.dart 28:7                   $checkedCreate.checkedConvert
package:flutter_gen_core/settings/pubspec.g.dart 19:38                  _$PubspecFromJson.<fn>
package:json_annotation/src/checked_helpers.dart 33:22                  $checkedCreate.<fn>
package:json_annotation/src/checked_helpers.dart 51:23                  $checkedNew
package:json_annotation/src/checked_helpers.dart 30:10                  $checkedCreate
package:flutter_gen_core/settings/pubspec.g.dart 9:40                   _$PubspecFromJson
package:flutter_gen_core/settings/pubspec.dart 15:41                    new Pubspec.fromJson
package:flutter_gen_core/settings/config.dart 28:27                     loadPubspecConfig
package:flutter_gen_core/settings/config.dart 34:12                     loadPubspecConfigOrNull
package:flutter_gen_runner/flutter_gen_runner.dart 23:24                FlutterGenBuilder._config
package:flutter_gen_runner/flutter_gen_runner.dart                      FlutterGenBuilder._config
package:flutter_gen_runner/flutter_gen_runner.dart 43:9                 FlutterGenBuilder.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33  _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9   new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 346:27  _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                               Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8   createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29           BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42          BuildRunner.create
package:build_runner/src/generate/build.dart 109:35                     build
package:build_runner/src/entrypoint/build.dart 35:18                    BuildCommand._run
package:args/command_runner.dart 212:13                                 CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                      run
.dart_tool/build/entrypoint/build.dart 29:16                            main
```

Does this type cast error ring a bell to someone?

**Comment by jeroenbloom** [comment]
Seeing it as well, but a slightly different error.

```
λ dart pub global run flutter_gen:flutter_gen_command

FlutterGen v5.3.2 Loading ... solarnative-app/pubspec.yaml
Unhandled exception:
CheckedFromJsonException
Could not create `FlutterGenIntegrations`.
There is a problem with "flutter_svg".
type 'String' is not a subtype of type 'bool' in type cast
#0      $checkedConvert (package:json_annotation/src/checked_helpers.dart:91:5)
#1      $checkedCreate.checkedConvert (package:json_annotation/src/checked_helpers.dart:28:7)
#2      _$FlutterGenIntegrationsFromJson.<anonymous closure> (package:flutter_gen_core/settings/pubspec.g.dart:173:38)
#3      $checkedCreate.<anonymous closure> (package:json_annotation/src/checked_helpers.dart:33:22)
#4      $checkedNew (package:json_annotation/src/checked_helpers.dart:51:23)
#5      $checkedCreate (package:json_annotation/src/checked_helpers.dart:30:10)
#6      _$FlutterGenIntegrationsFromJson (package:flutter_gen_core/settings/pubspec.g.dart:159:5)
#7      new FlutterGenIntegrations.fromJson (package:flutter_gen_core/settings/pubspec.dart:175:7)
#8      _$FlutterGenFromJson.<anonymous closure>.<anonymous closure> (package:flutter_gen_core/settings/pubspec.g.dart:88:61)
#9      $checkedConvert (package:json_annotation/src/checked_helpers.dart:87:20)
#10     $checkedCreate.checkedConvert (package:json_annotation/src/checked_helpers.dart:28:7)
#11     _$FlutterGenFromJson.<anonymous closure> (package:flutter_gen_core/settings/pubspec.g.dart:87:40)
#12     $checkedCreate.<anonymous closure> (package:json_annotation/src/checked_helpers.dart:33:22)
#13     $checkedNew (package:json_annotation/src/checked_helpers.dart:51:23)
#14     $checkedCreate (package:json_annotation/src/checked_helpers.dart:30:10)
#15     _$FlutterGenFromJson (package:flutter_gen_core/settings/pubspec.g.dart:65:46)
#16     new FlutterGen.fromJson (package:flutter_gen_core/settings/pubspec.dart:82:44)
#17     _$PubspecFromJson.<anonymous closure>.<anonymous closure> (package:flutter_gen_core/settings/pubspec.g.dart:20:48)
#18     $checkedConvert (package:json_annotation/src/checked_helpers.dart:87:20)
#19     $checkedCreate.checkedConvert (package:json_annotation/src/checked_helpers.dart:28:7)
#20     _$PubspecFromJson.<anonymous closure> (package:flutter_gen_core/settings/pubspec.g.dart:19:38)
#21     $checkedCreate.<anonymous closure> (package:json_annotation/src/checked_helpers.dart:33:22)
#22     $checkedNew (package:json_annotation/src/checked_helpers.dart:51:23)
#23     $checkedCreate (package:json_annotation/src/checked_helpers.dart:30:10)
#24     _$PubspecFromJson (package:flutter_gen_core/settings/pubspec.g.dart:9:40)
#25     new Pubspec.fromJson (package:flutter_gen_core/settings/pubspec.dart:15:41)
#26     loadPubspecConfig (package:flutter_gen_core/settings/config.dart:28:27)
#27     loadPubspecConfigOrNull (package:flutter_gen_core/settings/config.dart:34:12)
#28     FlutterGenerator.build (package:flutter_gen_core/flutter_generator.dart:25:16)
#29     main (file:///Users/jeroen/.pub-cache/hosted/pub.dev/flutter_gen-5.3.2/bin/flutter_gen_command.dart:48:49)
#30     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#31     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by jakemac53** [comment]
Looks like this is failing [here](https://github.com/FlutterGen/flutter_gen/blob/main/packages/core/lib/settings/pubspec.g.dart#L129). So you likely have some configuration for an `outputs` field, presumably in your `pubspec.yaml` file (just based on the library name).

It looks like you are just passing a String, but the package expects a Map.

If you have further questions I would file an issue on the `flutter_gen` package, and they should have more context.
