### ISSUE TITLE
Passing dart environment variables in `webdev build` or `webdev serve` throws type cast exception

### ISSUE THREAD

**Issue by ahmednfwela** [dart-lang/build#3716]
running 
```shell
webdev serve -- '--define=build_web_compilers:ddc=environment={"SOME_VAR":"changed"}'
```
or 
```shell
webdev build -- '--define=build_web_compilers:ddc=environment={"SOME_VAR":"changed"}'
```
as documented in `build_web_compilers` readme

https://github.com/dart-lang/build/blob/30c4459d347e6a4c33f2a7d923808c6d905170c2/build_web_compilers/README.md?plain=1#L99

throws:
```
[SEVERE] type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast

Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup.<anonymous closure> (package:build_daemon/client.dart:79:21)
#1      _runUserCode (dart:async/stream_pipe.dart:11:23)
#2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1708:9)
#3      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:399:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)      
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:398:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:268:5)
#11     _AsBroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:505:24)
#12     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#16     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#17     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#18     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#19     _LineSplitterSink.close (dart:convert/line_splitter.dart:141:11)
#20     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#21     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#22     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#23     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#24     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#25     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#26     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#27     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#28     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
#29     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#30     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#31     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#32     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#33     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#34     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#35     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#36     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#37     _StreamController.close (dart:async/stream_controller.dart:640:5)
#38     _Socket._onData (dart:io-patch/socket_patch.dart:2456:21)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#43     _StreamController._add (dart:async/stream_controller.dart:658:7)
#44     _StreamController.add (dart:async/stream_controller.dart:606:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1943:35)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1372:18)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#50     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
Building package executable... 
Built webdev:webdev.
```

---

* Dart SDK Version (`dart --version`): 3.4.3
* What package(s) from this repo you are using, and the version
  * `build_runner`: 2.4.10
  * `build_web_compilers`; 4.0.10
* What builder(s) you are using: mainly just `webdev build` and `webdev serve`
* Windows 11
* Chrome
* Any other packages or constraints we should know about: I am using `ngdart`

**Comment by jakemac53** [comment]
The command above works fine for me on Linux - are you on windows? Probably some additional escaping is needed?

**Comment by ahmednfwela** [comment]
yes, as stated in the issue I am running win 11 @jakemac53

**Comment by jakemac53** [comment]
@ahmednfwela I am not a windows user (at least not for development purposes), so I don't know exactly what to suggest. The command almost certainly just needs some escaping, maybe the `:` or something?

If you can figure out the command that does work, I would be happy to update the docs with something that works on windows (or merge a PR to update them).

**Comment by ahmednfwela** [comment]
@jakemac53 can you point me to the unit test covering this part in code?

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/blob/b3d3ef1c6981c92d5f513d31240aa2e340f19cd3/_test/test/dart2js_integration_test.dart#L35 and https://github.com/dart-lang/build/blob/b3d3ef1c6981c92d5f513d31240aa2e340f19cd3/_test/test/serve_integration_test.dart#L148 are probably the most relevant ones to this issue? If you search the repo for `--define` you will find some others.
